name: "Build & Push images"

on:
  push:
    paths:
      - '.github/workflows/main.yml'
      - 'Dockerfile'
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          V=18.04 && docker image build -t ubuntu-cn:$V --build-arg VERSION=$V .
          V=19.10 && docker image build -t ubuntu-cn:$V --build-arg VERSION=$V .
          V=20.04 && docker image build -t ubuntu-cn:$V --build-arg VERSION=$V .
          V=20.10 && docker image build -t ubuntu-cn:$V --build-arg VERSION=$V .
          V=14.04 && docker image build -t ubuntu-cn:$V --build-arg VERSION=$V .
          V=16.04 && docker image build -t ubuntu-cn:$V --build-arg VERSION=$V .
      - name: Tags
        run: |
          V=18.04 && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:$V \
            && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:18 \
            && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:bionic

          V=19.10 && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:$V \
            && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:19 \
            && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:eoan

          V=20.04 && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:$V \
            && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:20 \
            && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:focal \
            && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:latest

          V=20.10 && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:$V \
            && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:groovy \
            && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:dev

          V=14.04 && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:$V \
            && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:14 \
            && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:trusty

          V=16.04 && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:$V \
            && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:16 \
            && docker tag ubuntu-cn:$V ${{ secrets.DOCKER_USER }}/ubuntu-cn:xenial
          
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:18.04
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:18
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:bionic
          
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:19.10
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:19
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:eoan

          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:20.04
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:20
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:focal
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:latest

          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:20.10
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:groovy
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:dev

          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:14.04
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:14
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:trusty

          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:16.04
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:16
          docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:xenial
