name: "Build & Push images"

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/main.yml'
      - '.github/workflows/build-one-version.yml'
      - 'Dockerfile'
    branches:
      - master
  schedule:
    # https://crontab.guru/#0_0_*_*_0
    # At 00:00 on Sunday.
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        tags:
          - |
            14.04
            14
            trusty
          - |
            16.04
            16
            xenial
          - |
            18.04
            18
            bionic
          - |
            20.04
            20
            focal
          - |
            22.04
            22
            jammy
            latest
    uses: ./.github/workflows/build-one-version.yml
    with:
      tags: |
        ${{ matrix.tags }}
    secrets: inherit
