name: "Build & Push images"

on:
  push:
    paths:
      - '.github/workflows/main.yml'
      - 'Dockerfile'
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build-Tag-Push
        run: |
          # A tag name must be valid ASCII and 
          # may contain lowercase and uppercase letters, digits, underscores, periods and dashes.
          # A tag name may not start with a period or a dash and
          # may contain a maximum of 128 characters.
          version_keys=(v14 v16 v18 v19 v20 v201)
          v14=(14.04 14 trusty)
          v16=(16.04 16 xenial)
          v18=(18.04 18 bionic)
          v19=(19.10 19 eoan)
          v20=(20.04 20 focal latest)
          v201=(20.10 groovy dev)
          for k in "${version_keys[@]}"; do
            k=$k[@]
            tags=(${!k})
            VER=${tags[0]}
            docker image build -t ubuntu-cn:$VER --build-arg VERSION=$VER .
            for tag in ${tags[@]:1}; do
              docker tag ubuntu-cn:$VER ${{ secrets.DOCKER_USER }}/ubuntu-cn:$tag
              docker push ${{ secrets.DOCKER_USER }}/ubuntu-cn:$tag
            done;
          done;
